version: "3.8"
services:
  hadoop1:
    image: hadoop
    hostname: hadoop1
    container_name: hadoop1
    build: .
    volumes:
      - ./.data/:/data/
    ports:
      - "2222:22"
      - "9000:9000"
      - "9864:9864"
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"